### ISSUE TITLE
Application Icon

### ISSUE THREAD

**Issue by dridk** [labsquare/CutePeaks#15]
We need an application icon to release the app. 

See 4peaks icons : 
http://nucleobytes.com/4peaks/

@labsquare/designers need some help !

**Comment by it-s** [comment]
Could you provide a list of icons needed?
Example:
* Open file
* Save file

**Comment by dridk** [comment]
Only for the main application.
For exemple fastqt has already this icon: https://github.com/labsquare/fastQt/blob/master/fastqt.png

CutePeaks application could display trace curve : https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_o118elODQfCqYjFUyESoaX_G0qrPGfb68FHkC548Ib-Zeq-e
