### ISSUE TITLE
Logo application

### ISSUE THREAD

**Issue by dridk** [labsquare/CutePeaks#54]
Need a logo application to release cutepeaks 0.2 ! 
All contribution are welcome

**Comment by dridk** [comment]
Exemple of alternative software 
![image](https://user-images.githubusercontent.com/1911063/34308645-9686c224-e74e-11e7-99a4-ca6f43d3326f.png)

**Comment by dridk** [comment]
Mine test ! 
![2017-06-26](https://user-images.githubusercontent.com/1911063/34308783-38ce2bf8-e74f-11e7-8bf6-137fadbb4110.png)

**Comment by elioqoshi** [comment]
Sent an email yesterday :)

**Comment by dridk** [comment]
# labsquare poster design 
https://github.com/labsquare/Poster

# keyword ideas
DNA , ACGT, sequencing, read, electrophorgram

By default, 
A = Adenine = green
T = Tymine = red 
C = cytosine = blue
G = guanine = black

**Comment by dridk** [comment]
logo inspiration : 
![image](https://user-images.githubusercontent.com/1911063/34530587-ecea26b4-f0af-11e7-85ef-7e7e44fc8e22.png)

**Comment by Maurosa** [comment]
Can you tell me more about your version? What are the reasons behind the following choices:
the meaning behind the hexagon? is there a reason it is not quite perfectly drawn? the choice of color? specular reflection? Outline on the top but not on the bottom?
Anything would help. Thank you.

**Comment by dridk** [comment]
Hi, 
Thanks for your proposition. Unfortunally, @elioqoshi did the job. 

![unnamed 4](https://user-images.githubusercontent.com/1911063/34664299-7f91a1a0-f45b-11e7-96ba-eabb0180b681.png)
![unnamed 3](https://user-images.githubusercontent.com/1911063/34664301-80c36f0e-f45b-11e7-8344-a96eff307704.png)

**Comment by StuntsPT** [comment]
This reminds me of the CGA palette. =-)
Yeah, I'm getting old.
