### ISSUE TITLE
cannot deploy on travis 

### ISSUE THREAD

**Issue by dridk** [labsquare/CutePeaks#61]
Did not success to update travis to have upload feature 
https://github.com/labsquare/CutePeaks/blob/devel/.travis.yml
Probably caused by subfolder

**Comment by dridk** [comment]
@probonopd could you help me on this issue ?

**Comment by probonopd** [comment]
Looking at https://travis-ci.org/labsquare/CutePeaks/jobs/327779249#L622 this doesn't seem an "upload" issue. But `linuxdeployqt` doesn't seem to find the main executable binary. And indeed `appdir/usr/bin/...` does not seem to exist, probably due to https://travis-ci.org/labsquare/CutePeaks/jobs/327779249#L591, `make[1]: Nothing to be done for `install'`.

**Comment by dridk** [comment]
I don't understand...
Locally, it works, I have my bin directory.... But it doesn't appear on travis

➜  CutePeaks git:(devel) ✗ find appdir 
appdir
appdir/usr
appdir/usr/local
appdir/usr/local/bin
appdir/usr/local/bin/cutepeaks
appdir/usr/local/share
appdir/usr/local/share/icons
appdir/usr/local/share/icons/hicolor
appdir/usr/local/share/icons/hicolor/48x48
appdir/usr/local/share/icons/hicolor/48x48/apps
appdir/usr/local/share/icons/hicolor/48x48/apps/cutepeaks.png
appdir/usr/local/share/applications
appdir/usr/local/share/applications/cutepeaks.desktop

the main pro file (cutepeaks.pro) call the subdir src ( src.pro) here : https://github.com/labsquare/CutePeaks/blob/devel/cutepeaks.pro#L4

So , I have to set the binary path myself in INSTALL statement : 
https://github.com/labsquare/CutePeaks/blob/devel/cutepeaks.pro#L21

**Comment by probonopd** [comment]
Can you try with Ubuntu 14.04 (which is used on Travis CI) locally? E.g., using a Live ISO?

**Comment by dridk** [comment]
yes I will.. I did the copy myself and it works https://travis-ci.org/labsquare/CutePeaks/builds/327811892
But it's ugly :p

**Comment by dridk** [comment]
so .. I failed everything...  I will try next time . 
Shame on me.. I cannot release cutepeaks to answer this question :https://www.biostars.org/p/292960/

**Comment by probonopd** [comment]
So you successfully produced `cutepeaks-x86_64.AppImage` but are trying to upload `CutePeaks*.AppImage*`. Changing the Capitalization in the desktop file should do the trick.

**Comment by probonopd** [comment]
Err... actually it is "CutePeaks" in the desktop file.

https://github.com/labsquare/CutePeaks/blob/a0c51cf16d8fe617a7c32d338019ae32a6059c3a/cutepeaks.desktop#L3

So why is the AppImage all lowercase? Humm... linuxdeployqt bug?
