### ISSUE TITLE
Bug in amino acid translation

### ISSUE THREAD

**Issue by domenico-somma** [labsquare/CutePeaks#65]
There is something wrong in the amino acid translation. It doesn't correspond to the right one (tested more than one file)
![aa](https://user-images.githubusercontent.com/34346930/35573781-ed097f5c-05cf-11e8-9922-76056900591a.png)

**Comment by dridk** [comment]
Ouch.. that's a hug bug !

**Comment by dridk** [comment]
@domenico-somma I just uploaded  binary 0.2.1 for Linux . Mac and windows are comming
https://github.com/labsquare/CutePeaks/releases/tag/0.2.1

Sorry for this bug and thank for your issue
