### ISSUE TITLE
Bug: TAC/T codon wrongly translated

### ISSUE THREAD

**Issue by domenico-somma** [labsquare/CutePeaks#66]
Hi, I used the new version 0.2.1 .
TAC and TAT codons return Phe while should be Tyr.

![y wrong](https://user-images.githubusercontent.com/34346930/35631939-264e09cc-069d-11e8-851e-48cc19154d6d.png)

P.S. Don't you have a script test to check all the codon translations?

**Comment by dridk** [comment]
Ok, this is now a different bug comming from a wrong translation table:  https://github.com/labsquare/CutePeaks/blob/master/src/core/proteinalphabet.cpp

**Comment by dridk** [comment]
new release 0.2.2 with hotfix
https://github.com/labsquare/CutePeaks/releases/tag/0.2.2
